# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 248a2b7acb1dd792664b70c9c826aa0ee9bf9f22df8458f0a46490351d4cdca3bb8a41db241d1890103bf67bec916ab42615a59feeaa9ed346f7133345afe90e

test:
  secret_key_base: 574533e75536158e143ee86a75977fb93acdb62d4b74bf2197cd8aa809e534b9fc2f189b114eff1189a21bb702687448d9aed1a7235f17bec0044b7257676f70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
